config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#index'
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
require 'csv'

class Contact < ApplicationRecord


  private

  def self.load_csv
    CSV.foreach(Rails.root.join('db/contacts.csv'), headers: true) do |row|
      Contact.create(name: row[0], email: row[8], phone: row[11])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    if Contact.all.empty?
      Contact.load_csv
    end
    sql_query = "name ILIKE :name OR email ILIKE :email"

    @contacts = Contact.where(sql_query, name: params[:name], email: params[:email])

    if params[:query].present?
      sql_query = "name ILIKE :query OR email ILIKE :query OR cast(phone as text) ILIKE :query"

      @contacts = Contact.where(sql_query, query: params[:query])
    elsif !params[:query].present? && !params[:name].present? && !params[:email].present?
      @contacts = Contact.all
    end

  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.save
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :phone)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.html.erb
<div class="m-3">
  <%= form_tag contacts_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query] = '',
      class: "form-control-sm mb-4",
      placeholder: "Find a contact"
    %>
  <% end %>

  <% @contacts.each do |contact| %>
    <%= contact.name %>,
    <%= contact.email %>,
    <%= contact.phone %>
    <hr>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %>
  <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>

<body>
  <div class="banner">
    <div class="container">
      <h1>Let's conect! Here's your contacts.</h1>
    </div>
  </div>
  <%= yield %>
  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Home
  </div>
</div>

  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>